require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  Exclude:
    - "db/schema.rb"
    - "bin/**"
Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
Rails/FilePath:
  Exclude:
    - "spec/rails_helper.rb"
    - "config/environments/**"
Layout/LineLength:
  Exclude:
    - "config/initializers/**"
